### ISSUE TITLE
紧急：IP源关闭

### ISSUE THREAD

**Issue by lingbopro** [lingbopro/easy-github-hosts#17]
今天测试新功能的时候突然发现我们的IP源 `acme-check.com` 获取不到信息了，访问了一下才发现，网站维护了...  
希望不是因为我们测试的时候访问了太多次...  
需要**立即**选择一个新的源  

附截图：  
![image](https://github.com/lingbopro/easy-github-hosts/assets/148617407/2b075cbd-b8e4-47ec-b4c9-073630d9fde7)  

_（悲_

**Comment by lingbopro** [comment]
找到了一个：  
<http://ip-api.com>  

用着还算方便  
比如要查 `github.com` 的IP，只需要 GET：  
```
http://ip-api.com/json/github.com?fields=status,message,query
```
（不能用HTTPS，不然获取不到）

**Comment by Minemetero** [comment]
收到，已过审 (bushi

**Comment by Minemetero** [comment]
> 今天测试新功能的时候突然发现我们的IP源 `acme-check.com` 获取不到信息了，访问了一下才发现，网站维护了... 希望不是因为我们测试的时候访问了太多次... 需要**立即**选择一个新的源
> 
> 附截图： ![image](https://private-user-images.githubusercontent.com/148617407/335865514-2b075cbd-b8e4-47ec-b4c9-073630d9fde7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTc0MDEzMjgsIm5iZiI6MTcxNzQwMTAyOCwicGF0aCI6Ii8xNDg2MTc0MDcvMzM1ODY1NTE0LTJiMDc1Y2JkLWI4ZTQtNDdlYy1iNGM5LTA3MzYzMGQ5ZmRlNy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNjAzJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDYwM1QwNzUwMjhaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1mZGU3ODMyYWYyYzIzYTA3ZWI4MmI1ZDJkM2Q0NjlkZDY4ZGY0NTRiYWZmNjlkMjI4MWJlODUzM2RjYWY4NGUzJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.VrVwwme6tXklG_S2Wa-FY9jz4SzDXrQoHeOFnb0Vvm0)
> 
> _（悲_

变ddos了：） FBI要上门了

**Comment by Minemetero** [comment]
你知道吗？我邮箱里全是你的消息。

**Comment by Minemetero** [comment]
> 找到了一个： http://ip-api.com
> 
> 用着还算方便 比如要查 `github.com` 的IP，只需要 GET：
> 
> ```
> http://ip-api.com/json/github.com?fields=status,message,query
> ```
> 
> （不能用HTTPS，不然获取不到）

get 给我的第一反应是python requests库里的函数get

**Comment by lingbopro** [comment]
> 你知道吗？我邮箱里全是你的消息。
> 
> 时刻警惕着我，我手上有个开源项目。。。。

啊？

**Comment by lingbopro** [comment]
> > 找到了一个： http://ip-api.com
> > 
> > 用着还算方便 比如要查 `github.com` 的IP，只需要 GET：
> > 
> > ```
> > http://ip-api.com/json/github.com?fields=status,message,query
> > ```
> > 
> > （不能用HTTPS，不然获取不到）
> 
> get 给我的第一反应是python requests库里的函数get

也没毛病，毕竟是HTTP方法`GET`

**Comment by lingbopro** [comment]
不过这个有一个问题  
就是这个API每分钟好像只能请求三十几次  

----

功能的话，今天我看看有没有时间吧  
毕竟快期末了（

**Comment by Minemetero** [comment]
> 不过这个有一个问题 就是这个API每分钟好像只能请求三十几次
> 
> 功能的话，今天我看看有没有时间吧 毕竟快期末了（

我現在在去打網球的路上，再過2個小時我回家看看

**Comment by lingbopro** [comment]
文档里的描述是每分钟45次  

![Screenshot_20240603_165639.jpg](https://github.com/lingbopro/easy-github-hosts/assets/148617407/87415e5c-6f0c-4061-8cf9-9229a28ae978)  

这个项目里有37个URL，未来可能有更多  
我觉得目前可以采用，不过之后还可以在看别的或者精简URL列表什么的

**Comment by Minemetero** [comment]
非常可以，你可以开始干活了

**Comment by Minemetero** [comment]
不对不对，这个是只能查IPv4和IPv6的地址吧，我没看到可以输入URL啊

**Comment by lingbopro** [comment]
> 不对不对，这个是只能查IPv4和IPv6的地址吧，我没看到可以输入URL啊

可以的

**Comment by lingbopro** [comment]
> 非常可以，你可以开始干活了
> 先慢慢加吧，在dev分支里慢慢加，慢慢做

今天肯定做不完了  
得过两天才能做完

**Comment by Minemetero** [comment]
你每次都说过两天所以你啥时才正式开始干呢？还要再等多少个两天呢？(没有任何其他的意思，相信我)

**Comment by lingbopro** [comment]
我发PR了  
#19  

这个issue可以关了

**Comment by Minemetero** [comment]
> 我发PR了 #19
> 
> 这个issue可以关了

我刚上完课呢

**Comment by lingbopro** [comment]
> > 我发PR了 #19
> > 这个issue可以关了
> 
> 我刚上完课呢

a
