### ISSUE TITLE
Node 运行程序的指令在sudo下是什么啊

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/easy-github-hosts#2]
我直接sudo node main.js他说没这个指令。。。。

**Comment by lingbopro** [comment]
啊？
你装Node.js了吗

另外能给我发一下错误的提示吗

**Comment by lingbopro** [comment]
另外你不会是Windows吧

Windows直接以管理员运行cmd就行

**Comment by Minemetero** [comment]
我没那么白痴

**Comment by lingbopro** [comment]
> 我没那么白痴

所以提示了什么

**Comment by Minemetero** [comment]
没权限

**Comment by Minemetero** [comment]
我试着加了sudo但是sudo下面没有node

**Comment by Minemetero** [comment]
Contributors

> 啊？ 你装Node.js了吗
> 
> 另外能给我发一下错误的提示吗

Linux 机器不在我边上。。。

**Comment by lingbopro** [comment]
> 没权限

emmm  
会不会你的账户不在sudoers里，所以用不了

**Comment by Minemetero** [comment]
我只有一个账号不可能的问题，你没意识到问题所在

**Comment by Minemetero** [comment]
问题是在sudo下面没有node这个指令

**Comment by Minemetero** [comment]
不管了，我看你玩Roblox是吧

**Comment by Minemetero** [comment]
话说你为啥follow我啊

**Comment by lingbopro** [comment]
> 问题是在sudo下面没有node这个指令

啊？  
按理来说sudo只是执行后面的指令，所以如果没sudo可以正常使用node那sudo也行啊  
要么就是node没装上/没注册上环境变量导致的找不到命令  
我只能想到这些可能性了…

**Comment by lingbopro** [comment]
> 话说你为啥follow我啊

从忘了那个repo里看到的，然后就follow了呗:)

**Comment by Minemetero** [comment]
真随意。。。

**Comment by Minemetero** [comment]
你玩什么Minecraft 服务器

**Comment by lingbopro** [comment]
> 你玩什么Minecraft 服务器

基本上玩单人吧  
要不然就是开个内网穿透，跟朋友玩

**Comment by Minemetero** [comment]
> > 你玩什么Minecraft 服务器
> 
> 基本上玩单人吧 要不然就是开个内网穿透，跟朋友玩

懂了

**Comment by Minemetero** [comment]
> > 话说你为啥follow我啊
> 
> 从忘了哪个repo里看到的，然后就follow了呗:)

茫茫人海里你能找到我是我的荣幸

**Comment by lingbopro** [comment]
> > > 话说你为啥follow我啊
> > 
> > 从忘了哪个repo里看到的，然后就follow了呗:)
> 
> 茫茫人海里你能找到我是我的荣幸

:)

**Comment by lingbopro** [comment]
这个issue关了吧
