### ISSUE TITLE
Suggestion: Package All

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/easy-github-hosts#3]
我觉得这个仓库的实用性不太高，大部分人会选择手动添加，毕竟还要搭建node的环境反而复杂了，最好变成双击启动程序就啥都搞定了。

**Comment by Minemetero** [comment]
理论上可以结合bash实现呢

**Comment by lingbopro** [comment]
但是问题在于这个repo是用Node.js写的，要想直接启动就得把node环境打包进去，但是这样会导致包特别的大，而GitHub国内下载速度超级慢...  
~~而且你都上GitHub了你还嫌什么操作麻烦~~

**Comment by zsr-lukezhang** [comment]
直接开镜像站？

**Comment by zsr-lukezhang** [comment]
但实际上镜像也很慢
最好的办法就是梯子

**Comment by lingbopro** [comment]
> 但实际上镜像也很慢
> 最好的办法就是梯子

笑死，买不起服务器（

**Comment by lingbopro** [comment]
等一下…

@Minemetero 我们收到的第一个来自其他人的评论！！（十分甚至二十分的激动

**Comment by zsr-lukezhang** [comment]
什么服务器？

**Comment by zsr-lukezhang** [comment]
啊这...

**Comment by Minemetero** [comment]
> Owner

ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh 我们的项目被人光顾了

**Comment by Minemetero** [comment]
> 等一下…
> 
> @Minemetero 我们收到的第一个来自其他人的评论！！（十分甚至二十分的激动

ohhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhhh 我们的项目被人光顾了

**Comment by Minemetero** [comment]
> 什么服务器？

你不把你的文件托管到服务器上？他们从哪下载，凭空而来？

**Comment by zsr-lukezhang** [comment]
我只是随便看一下（
服务器？在Releases里扔一个OneDrive链接就好了（MSFT E5开发者计划可以免费高速）

**Comment by Minemetero** [comment]
> 我只是随便看一下（ 服务器？在Releases里扔一个OneDrive链接就好了（MSFT E5开发者计划可以免费高速）

那不一样的是在国外嘛。。。。。

**Comment by Minemetero** [comment]
> 我只是随便看一下（ 服务器？在Releases里扔一个OneDrive链接就好了（MSFT E5开发者计划可以免费高速）

话说你记得留下你的star啊！！！！

**Comment by zsr-lukezhang** [comment]
好的

**Comment by zsr-lukezhang** [comment]
<img width="120" alt="image" src="https://github.com/lingbopro/easy-github-hosts/assets/145239958/8d90014d-1fe0-42a6-a7f9-534d4eef2da0">
而且国外？国内也可以啊

**Comment by Minemetero** [comment]
> 好的

你可以看看我们其他repo如果乐意的话欢迎PR

**Comment by Minemetero** [comment]
> <img alt="image" width="120" src="https://private-user-images.githubusercontent.com/145239958/347833110-8d90014d-1fe0-42a6-a7f9-534d4eef2da0.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjA3MDQ0MTMsIm5iZiI6MTcyMDcwNDExMywicGF0aCI6Ii8xNDUyMzk5NTgvMzQ3ODMzMTEwLThkOTAwMTRkLTFmZTAtNDJhNi1hN2Y5LTUzNGQ0ZWVmMmRhMC5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNzExJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDcxMVQxMzIxNTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT03YjFkMTQ0NGM5ODdhNjMwMDUzODQzMjViNDNhYzMyODFlMjlhYmE4ZmMwOGFlNDI5NGVlNzBlMjNkZmIyZmY0JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.wAT_9fVkSECloBAdiEY7OGldLGnOQij3yHR2ZkA5Yp4"> 而且国外？国内也可以啊

e?没理解

**Comment by zsr-lukezhang** [comment]
E5开发是沙盒企业版，速度很快

**Comment by Minemetero** [comment]
> E5开发是沙盒企业版，速度很快

我们移步Disscussion谢谢

**Comment by lingbopro** [comment]
哦？

**Comment by Minemetero** [comment]
closed this as [not planned](https://github.com/lingbopro/easy-github-hosts/issues?q=is%3Aissue+is%3Aclosed+archived%3Afalse+reason%3A%22not+planned%22) [33 minutes ago](https://github.com/lingbopro/easy-github-hosts/issues/3#event-14036629561)

**Comment by Minemetero** [comment]
Not planned
反正不干我干脆关了

**Comment by lingbopro** [comment]
emmm
