### ISSUE TITLE
请求: 重新编译

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/easy-github-hosts#5]
我想用Python重新编译一遍,用JS实在是太奇怪了...
我想试试,如果成了你就给我搞个branch或者我自立仓库然后各奔东西.
主要是我比较熟悉Python..我觉得Python更加有开创空间...

**Comment by Minemetero** [comment]
根据MIT我可以这样干吧而且都不是一个语言,但是我希望合并到这个仓库,如果我成功了.

**Comment by lingbopro** [comment]
也行，不过如果换语言了就可以开个新的repo了
