### ISSUE TITLE
几个小请求

### ISSUE THREAD

**Issue by Minemetero** [lingbopro/easy-github-hosts#8]
MIT 的证书可不可以留下我的名字:) 
顺便给我repo的管理权给我一条branch的管理权,我的代码就可以合并进去啦
如果别人有issue的话(不太可能)我还可以帮你康康:)

**Comment by lingbopro** [comment]
> MIT 的证书可不可以留下我的名字:) 
> 顺便给我repo的管理权给我一条branch的管理权,我的代码就可以合并进去啦
> 如果别人有issue的话(不太可能)我还可以帮你康康:)

开源许可...可以有多个名字吗？（疑惑  
管理的话，回头我在网页版给你一个

**Comment by Minemetero** [comment]
你去看看PR

**Comment by lingbopro** [comment]
> 你去看看新的PR
> 
> 你看看我们的隔壁邻居
> https://github.com/docmirror/dev-sidecar
> 还玩个pi啊

没事  
主打一个开心就行（

**Comment by Minemetero** [comment]
.....
你去看看我的新PR

**Comment by lingbopro** [comment]
> .....
> 你去看看我的新PR

看了  
你看看我回复的
